# Generated by Django 5.0.3 on 2024-03-21 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_parent_assigned_by_student_enrolled_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_of",
                to="users.student",
            ),
        ),
    ]
