# Generated by Django 5.0.3 on 2024-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_profile_email_profile_is_verified_profile_phone2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
