# Generated by Django 5.0.3 on 2024-05-30 03:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_parent_is_active_profile_is_active_student_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone2",
        ),
    ]
