# Generated by Django 5.0.3 on 2024-05-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_report_approved_by_report_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="image_url",
            field=models.TextField(null=True),
        ),
    ]
